### ISSUE TITLE
Crashes on Win10 v1709

### ISSUE THREAD

**Issue by Darthagnon** [builtbybel/patchfluent#1]
I'm running Win10 v1709 with updates turned off via [Winaero Tweaker](https://winaero.com/comment.php?comment.news.1836). When I launch Patchfluent/Patchlady or Windows10ManualUpdate, the program crashes with the same error:

## Exception has occured!
```
System.Runtime.InteropServices.COMException (0x80070422): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422)
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject , String )
   at
System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at
System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Patchfluent.MainWindow.<SearchForUpdates>b__3_0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Patchfluent.MainWindow.<SearchForUpdates>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Patchfluent.MainWindow.<OnActivated>d__4.MoveNext()
```
   ### [   OK   ]

Hopefully I typed it right; couldn't copy from the window.

**Comment by Belim** [comment]
There is difference between disabling automatic updates and the disabling the Windows update service. 
If you completely disable the last story you will get excatly this error message and the app is useless. 
**Reversely, this means the Update service must be enabled**

**Comment by Darthagnon** [comment]
Is it possible to disable auto updates?!

**Comment by Belim** [comment]
> Is it possible to disable auto updates?!

Of course, it's describe here
https://github.com/builtbybel/patchfluent#how-to

I will add for sure some built-in app options for this task in upcoming versions

**Comment by Darthagnon** [comment]
Wondering, would it be possible for you to add the option to enable/disable the Update service via a visible switch in the Patchfluent UI? Just to ensure that Windows doesn't start downloading updates automatically (only way I have found to completely avoid this is to disable the service)

**Comment by Belim** [comment]
the only way to to this is to disable automatic updates (i'm definitely putting something in there) and not to open the native Windows 10 update page at all. 
After that you could use Patchfluent exclusively for this task. This is how i do it with some of my customers before starting with my work.

**Comment by Darthagnon** [comment]
That would be ideal, as Patchfluent has a better UI than both WinaeroTweaker and native Win10 for managing updates!

**Comment by Belim** [comment]
:smiley:
https://github.com/builtbybel/patchfluent/releases/tag/0.11.7

**Comment by litojero** [comment]
when I put automatic updates the program closes :(
